[project]
name = "wiggle-backend"
version = "0.1.0"
description = "Backend testing utilities for Wiggle project"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "modal>=0.63.0",
]
